# Generated by Django 3.2.21 on 2023-10-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_site', '0003_auto_20230927_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
