# Generated by Django 3.2.21 on 2023-10-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_site', '0005_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='recipe_site.post'),
        ),
    ]
