# Generated by Django 3.2.21 on 2023-10-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_site', '0008_post_excerpt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMe',
        ),
    ]
