# Generated by Django 3.2.21 on 2023-10-19 10:50

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_site', '0011_post_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('drinks_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('excerpt', models.TextField(blank=True)),
                ('prep_time', models.CharField(max_length=30)),
                ('ingredients', models.TextField()),
                ('drink_steps', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Posted')], default=0)),
                ('category', models.IntegerField(choices=[(0, 'Drinks'), (1, 'AirFryer')], default=0)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='drink_bookmark', to=settings.AUTH_USER_MODEL)),
                ('hearts', models.ManyToManyField(blank=True, related_name='drink_hearts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='drink_likes', to=settings.AUTH_USER_MODEL)),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
